name: Static Analysis

on:
  workflow_call:
    inputs:
      matrix:
        description: The strategy-matrix for OS, Xcode & Swift version
        required: true
        type: string
      source-root:
        description: Path to the root source code directory, relative to $GITHUB_WORKSPACE
        required: false
        type: string
        default: .

concurrency:
  group: analysis-${{ github.ref }}
  cancel-in-progress: true

jobs:
  codeql:
    name: On ${{ matrix.os }} with Swift ${{ matrix.swift }}
    runs-on: ${{ matrix.os }}
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      matrix: ${{ fromJSON(inputs.matrix) }}
    defaults:
      run:
        working-directory: ${{ inputs.source-root }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: danthorpe/ci/actions/setup@main
        with:
          swift: ${{ matrix.swift }}
          xcode: ${{ matrix.xcode }}

      - name: Init CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
          source-root: ${{ inputs.source-root }}

      - name: Build
        run: swift build --build-tests

      - name: Perfom Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:${{ matrix.language }}"
